pdark: 1.0e-8
ηd: 0.3
Lgt: 0
em: 0.03
η: 0.3
N: 16
ξ: 0.21
Ntot: 1.0e+14
logNtot: 14
ε0: 1.0e-20
ε1: 1.0e-10
ε2: 1.0e-20
εcor: 1.0e-20
εPA: 1.65e-20
f: 1.1
mode: "DP"
number_of_states: 4
number_of_vector: 4
cpstates: 8
modes:
 - "DP"
 - "CP_Ma"
 - "DP_Cao"

number_of_Ntots: 4
logNtots:
 - 12
 - 13
 - 14
 - 20

lemma: 'lemma2'